baseURL: https://cycling.paluchowski.com/
languageCode: en-us
title: Edge
theme: edge
sectionPagesMenu: main
googleAnalytics: G-V8734ZHR0G
markup:
    goldmark:
        renderer:
            unsafe: true
copyright: Published by <a href="https://michal.paluchowski.com/">Micha≈Ç Paluchowski</a>. All content is under a <a href="https://creativecommons.org/licenses/by/4.0/" rel="license">Creative Commons Attribution 4.0 International License</a>.
params:
    Subtitle: Cycling Contemplations
    Description: I'm a mediocre cyclist, sweating hard to improve. Here I share my findings, concerns and questions.
    Favicon:
        Image: /favicon.png
        Type: image/png
    Strava:
        AthleteId: 17745574
        WidgetId: 00ce09fd56e435e96d599ec456e44ef89d58c082
